{{- if not .Values.honeycomb.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: honeycomb-{{ include "opentelemetry-collector.fullname" . }}
  labels:
  {{- include "opentelemetry-collector.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.honeycomb.apiKey | b64enc | quote }}
{{- end }}
