apiVersion: v1
kind: Service
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $port := .Values.ports }}
    {{- if $port.enabled }}
    - name: {{ $key }}
      port: {{ $port.servicePort }}
      targetPort: {{ $key }}
      protocol: {{ $port.protocol }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "opentelemetry-collector.selectorLabels" . | nindent 4 }}
