apiVersion: v1
kind: Service
metadata:
  name: {{ include "htp-builder.fullname" . }}-beekeeper
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "htp-builder.beekeeper.labels" . | nindent 4 }}
    app.kubernetes.io/component: beekeeper
spec:
  type: ClusterIP
  ports:
    - port: 4320
      targetPort: "opamp"
      protocol: TCP
      name: opamp
  selector:
    {{- include "htp-builder.beekeeper.selectorLabels" . | nindent 4 }}
