{{- if .Values.beekeeper.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "htp-builder.beekeeper.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "htp-builder.beekeeper.labels" . | nindent 4 }}
    app.kubernetes.io/component: beekeeper
{{- end }}
