apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "htp-builder.fullname" . }}-beekeeper
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "htp-builder.beekeeper.labels" . | nindent 4 }}
    app.kubernetes.io/component: beekeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "htp-builder.beekeeper.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        {{- include "htp-builder.beekeeper.configTemplateChecksumAnnotation" . | nindent 8 }}
      labels:
        {{- include "htp-builder.beekeeper.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: beekeeper
    spec:
      serviceAccountName: {{ include "htp-builder.beekeeper.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.beekeeper.image.repository }}:{{ .Values.beekeeper.image.tag }}"
          imagePullPolicy: {{ .Values.beekeeper.image.pullPolicy }}
          {{- if or .Values.beekeeper.telemetry.enabled .Values.beekeeper.persistentVolumeClaimName }}
          args:
          {{- if .Values.beekeeper.telemetry.enabled }}
            - -otel-config
            - /etc/beekeeper/otel-config.yaml
          {{- end }}
          {{- if .Values.beekeeper.persistentVolumeClaimName }}
            - -config-cache-path
            - /app/beekeeper/cache
          {{- end }}
          {{- end }}
          env:
            - name: K8S_NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8S_POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: pipeline.id={{ .Values.pipeline.id }},k8s.namespace.name=$(K8S_NAMESPACE_NAME),k8s.node.name=$(K8S_NODE_NAME),k8s.pod.name=$(K8S_POD_NAME),k8s.pod.uid=$(K8S_POD_UID)
            - name: BEEKEEPER_HONEYCOMB_API
              value: {{ include "htp-builder.beekeeper.endpoint" . }}
            - name: BEEKEEPER_HONEYCOMB_INSTALLATION_ID
              value: {{ .Values.pipeline.id }}
            - name: BEEKEEPER_HONEYCOMB_MGMT_API_KEY
              value: {{ .Values.managementApiKey.id }}
            - name: BEEKEEPER_HONEYCOMB_MGMT_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.managementApiKey.secret.name }}
                  key: {{ .Values.managementApiKey.secret.key }}
            - name: BEEKEEPER_HONEYCOMB_API_KEY
              {{- if .Values.telemetry.ingestKey.value }}
              value: {{ .Values.telemetry.ingestKey.value }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.telemetry.ingestKey.secret.name }}
                  key: {{ .Values.telemetry.ingestKey.secret.key }}
              {{- end }}
            {{- if .Values.beekeeper.defaultEnv.BEEKEEPER_LOG_LEVEL.enabled }}
            - name: BEEKEEPER_LOG_LEVEL
              {{- toYaml .Values.beekeeper.defaultEnv.BEEKEEPER_LOG_LEVEL.content | nindent 14 }}  
            {{- end }}
            {{- if .Values.beekeeper.defaultEnv.BEEKEEPER_HONEYCOMB_CONFIGURATION_KEY.enabled }}
            - name: BEEKEEPER_HONEYCOMB_CONFIGURATION_KEY
              {{- toYaml .Values.beekeeper.defaultEnv.BEEKEEPER_HONEYCOMB_CONFIGURATION_KEY.content | nindent 14 }}  
            {{- end }}
            {{- if .Values.beekeeper.defaultEnv.BEEKEEPER_DEPLOYMENT_BATCH_SIZE.enabled }}
            - name: BEEKEEPER_DEPLOYMENT_BATCH_SIZE
              {{- toYaml .Values.beekeeper.defaultEnv.BEEKEEPER_DEPLOYMENT_BATCH_SIZE.content | nindent 14 }}  
            {{- end }}
            {{- with .Values.beekeeper.extraEnvs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.beekeeper.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.beekeeper.volumeMounts .Values.beekeeper.telemetry.enabled .Values.beekeeper.persistentVolumeClaimName }}
          volumeMounts:
          {{- if .Values.beekeeper.telemetry.enabled }}
            - name: otel-config
              mountPath: /etc/beekeeper
          {{- end }}  
          {{- if .Values.beekeeper.persistentVolumeClaimName }}
            - name: latest-config-cache
              mountPath: /app/beekeeper/cache
              readonly: false
          {{- end }}
          {{- with .Values.beekeeper.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          ports:
            - name: opamp
              containerPort: 4320
              protocol: TCP
      {{- if or .Values.beekeeper.volumeMounts .Values.beekeeper.telemetry.enabled .Values.beekeeper.persistentVolumeClaimName }}
      volumes:
      {{- if .Values.beekeeper.telemetry.enabled }}
        - name: otel-config
          configMap:
            name: {{ include "htp-builder.fullname" . }}-beekeeper
            items:
              - key: otel-config
                path: otel-config.yaml
      {{- end }}  
      {{- if .Values.beekeeper.persistentVolumeClaimName }}
        - name: latest-config-cache
          persistentVolumeClaimName: {{ .Values.beekeeper.persistentVolumeClaimName }}
      {{- end }}
      {{- with .Values.beekeeper.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
