{{- if .Values.primaryCollector.agent.telemetry.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "htp-builder.fullname" . }}-primary-collector-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "htp-builder.primaryCollector.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
data:
  config: |
  {{- include "htp-builder.primaryCollector.agent.config" . | nindent 4 -}}
{{- end }}
