apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "htp-builder.fullname" . }}-primary-collector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "htp-builder.primaryCollector.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
spec:
  replicas: {{ .Values.primaryCollector.replicaCount }}
  selector:
    matchLabels:
      {{- include "htp-builder.primaryCollector.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        {{- include "htp-builder.primaryCollector.configTemplateChecksumAnnotation" . | nindent 8 }}
        {{- if .Values.primaryCollector.agent.telemetry.enabled }}
        {{- include "htp-builder.primaryCollector.agent.configTemplateChecksumAnnotation" . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "htp-builder.primaryCollector.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: collector
    spec:
      serviceAccountName: {{ include "htp-builder.primaryCollector.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.primaryCollector.image.repository }}:{{ .Values.primaryCollector.image.tag }}"
          imagePullPolicy: {{ .Values.primaryCollector.image.pullPolicy }}
          args:
            - --config
            - /etc/opampsupervisor/config.yaml
          env:
            - name: K8S_NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8S_POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: STRAWS_COLLECTOR_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: pipeline.id={{ .Values.pipeline.id }},k8s.namespace.name=$(K8S_NAMESPACE_NAME),k8s.node.name=$(K8S_NODE_NAME),k8s.pod.name=$(K8S_POD_NAME),k8s.pod.uid=$(K8S_POD_UID)
            - name: HONEYCOMB_EXPORTER_APIKEY
              {{- if .Values.ingestKey.value }}
              value: {{ .Values.ingestKey.value }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ingestKey.secret.name }}
                  key: {{ .Values.ingestKey.secret.key }}
              {{- end }}
            {{- if .Values.primaryCollector.defaultEnv.HONEYCOMB_API_KEY.enabled }}
            - name: HONEYCOMB_API_KEY
              {{- toYaml .Values.primaryCollector.defaultEnv.HONEYCOMB_API_KEY.content | nindent 14 }}  
            {{- end }}
            {{- if .Values.primaryCollector.defaultEnv.STRAWS_REFINERY_SERVICE.enabled }}
            - name: STRAWS_REFINERY_SERVICE
              {{- tpl (toYaml .Values.primaryCollector.defaultEnv.STRAWS_REFINERY_SERVICE.content) . | nindent 14 }}  
            {{- end }}
            {{- with .Values.primaryCollector.extraEnvs }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.primaryCollector.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/opampsupervisor
            {{- if .Values.primaryCollector.agent.telemetry.enabled }}
            - name: agent-config
              mountPath: /etc/agent
            {{- end }}
          {{- with .Values.beekeeper.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "htp-builder.fullname" . }}-primary-collector
            items:
              - key: config
                path: config.yaml
        {{- if .Values.primaryCollector.agent.telemetry.enabled }}
        - name: agent-config
          configMap:
            name: {{ include "htp-builder.fullname" . }}-primary-collector-agent
            items:
              - key: config
                path: config.yaml
        {{- end }}
      {{- with .Values.primaryCollector.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
