{{- if .Values.primaryCollector.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "htp-builder.primaryCollector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "htp-builder.primaryCollector.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
{{- end }}
