{{- if .Values.refinery.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "htp-builder.refinery.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "htp-builder.refinery.labels" . | nindent 4 }}
    app.kubernetes.io/component: refinery
{{- end }}
