apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "htp-builder.fullname" . }}-refinery-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "htp-builder.refinery.labels" . | nindent 4 }}
    app.kubernetes.io/component: refinery
data:
  config.yaml: |
  {{- include "htp-builder.refinery.config" . | nindent 4 -}}
