version: 2
jobs:
  release-charts:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            echo "export GIT_USERNAME=$CIRCLE_USERNAME" >> $BASH_ENV
            echo "export GIT_REPOSITORY_URL=$CIRCLE_REPOSITORY_URL" >> $BASH_ENV
            echo "export GIT_REPOSITORY_OWNER=$CIRCLE_PROJECT_USERNAME" >> $BASH_ENV
            echo "export GIT_REPOSITORY_NAME=$CIRCLE_PROJECT_REPONAME" >> $BASH_ENV
            .circleci/install_tools.sh
            .circleci/release.sh
workflows:
  version: 2
  release:
    jobs:
      - release-charts:
          context: Honeycomb Secrets for Public Repos
          filters:
            tags:
              only: /^v[0-9].+-.*/
            branches:
              ignore: /.*/
