apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "network-agent.fullname" . }}
  labels:
    {{- include "network-agent.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "services"]
    verbs: ["get","watch","list"]
