apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "network-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "network-agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "network-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "network-agent.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "network-agent.fullname" . }}
      hostNetwork: true
      containers:
        - name: hny-network-agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HONEYCOMB_API_KEY
              valueFrom:
                secretKeyRef:
                  {{- if .Values.honeycomb.existingSecret }}
                  name: {{ .Values.honeycomb.existingSecret }}
                  key: {{ .Values.honeycomb.existingSecretKey }}
                  {{- else }}
                  name: {{ include "network-agent.fullname" . }}
                  key: apiKey
                  {{- end }}
            - name: HONEYCOMB_API_ENDPOINT
              value: {{ .Values.honeycomb.endpoint }}
            - name: HONEYCOMB_DATASET
              value: {{ .Values.honeycomb.dataset }}
            - name: HONEYCOMB_STATS_DATASET
              value: {{ .Values.honeycomb.statsDataset }}
            {{- with .Values.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            # https://kubernetes.io/docs/concepts/workloads/pods/downward-api/
            - name: AGENT_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: AGENT_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: AGENT_SERVICE_ACCOUNT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: AGENT_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: AGENT_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          securityContext:
            capabilities:
              add:
                - NET_RAW
