apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "hny-network-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "hny-network-agent.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.image.tag | default .Chart.AppVersion | quote }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hny-network-agent.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hny-network-agent.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Values.image.tag | default .Chart.AppVersion | quote }}
    spec:
      serviceAccountName: {{ include "hny-network-agent.fullname" . }}
      hostNetwork: true
      containers:
        - name: hny-network-agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HONEYCOMB_API_KEY
              valueFrom:
                secretKeyRef:
                  {{- if .Values.honeycomb.existingSecret }}
                  name: {{ .Values.honeycomb.existingSecret }}
                  key: {{ .Values.honeycomb.existingSecretKey }}
                  {{- else }}
                  name: {{ include "hny-network-agent.fullname" . }}
                  key: apiKey
                  {{- end }}
            - name: HONEYCOMB_API_ENDPOINT
              value: {{ .Values.honeycomb.endpoint }}
            - name: HONEYCOMB_DATASET
              value: {{ .Values.honeycomb.dataset }}
            - name: HONEYCOMB_STATS_DATASET
              value: {{ .Values.honeycomb.statsDataset }}
          securityContext:
            capabilities:
              add:
                - NET_RAW
