{{- if not .Values.honeycomb.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "network-agent.fullname" . }}
  labels:
    {{- include "network-agent.labels" . | nindent 4 }}
type: Opaque
data:
  apiKey: {{ .Values.honeycomb.apiKey | b64enc | quote }}
{{- end }}
