{{- if not .Values.honeycomb.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hny-network-agent.fullname" . }}
type: Opaque
data:
  apiKey: {{ .Values.honeycomb.apiKey | b64enc | quote }}
{{- end }}
