apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hny-network-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hny-network-agent.labels" . | nindent 4 }}
