{{ if not .Values.config.RulesConfigMapName }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "refinery.fullname" . }}-rules
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "refinery.labels" . | nindent 4 }}
data:
  rules.yaml: |
{{- toYaml .Values.rules | nindent 4 }}

{{ end }}
