apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "refinery.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  {{- with .Values.configMap.annotations }}
  annotations:
    {{ toYaml . | nindent 4  }}
  {{- end }}
  labels:
  {{- include "refinery.labels" . | nindent 4 }}
  {{- with .Values.configMap.labels }}
    {{ toYaml . | nindent 4  }}
  {{- end }}
data:
  config.yaml: |
  {{- include "refinery.config" . | nindent 4 -}}
