apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "refinery.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "refinery.labels" . | nindent 4 }}
data:
  config.yaml: |
  {{- include "refinery.config" . | nindent 4 -}}
