{{- if .Values.secretProvider.create -}}
apiVersion: v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProvider.name }}
  namespace: {{ .Release.Namespace }}
  spec:
    {{- with .Values.secretProvider.spec }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
