{{- if .Values.secretProvider.create -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProvider.name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.secretProvider.annotations }}
    annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "refinery.labels" . | nindent 4 }}
    {{- with .Values.secretProvider.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.secretProvider.spec }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
