apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secure-tenancy.fullname" . }}
  labels:
    {{- include "secure-tenancy.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "secure-tenancy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "secure-tenancy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/srv/hny/bin/honeycomb_secure_proxy"     
            - "-hnyconfig=/config/hnyconfig.yaml"
            - "-mysqlconfig=/config/mysqlconfig.yaml"
            - "-transformer={{ .Values.honeycomb.transformer }}"
          env:
            - name: HONEYCOMB_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "secure-tenancy.fullname" . }}
                  key: auth-token
            {{- if .Values.metrics.apiKey }}
            - name: LIBHONEY_WRITE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "secure-tenancy.fullname" . }}
                  key: libhoney-api-key
            {{- end }}
            - name: HONEYCOMB_MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "secure-tenancy.fullname" . }}
                  key: mysql-user
            - name: HONEYCOMB_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "secure-tenancy.fullname" . }}
                  key: mysql-password
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
          - name: config
            mountPath: /config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "secure-tenancy.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
