apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secure-tenancy.fullname" . }}
  labels:
  {{- include "secure-tenancy.labels" . | nindent 4 }}
type: Opaque
data:
  auth-token: {{ .Values.honeycomb.authToken | b64enc | quote }}
  {{- if .Values.metrics.apiKey }}
  libhoney-api-key: {{ .Values.metrics.apiKey | b64enc | quote }}
  {{- end }}
  mysql-user: {{ .Values.mysql.db.user | b64enc | quote }}
  mysql-password: {{ .Values.mysql.db.password | b64enc | quote }}
