apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "honeycomb.agent.fullname" . }}
  labels:
    {{- include "honeycomb.agent.labels" . | nindent 4 }}
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "honeycomb.agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        {{- if not .Values.honeycomb.existingSecret }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}  
        {{- end }}
        {{- with .Values.podAnnotations }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "honeycomb.agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "honeycomb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: honeycomb-agent
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HONEYCOMB_APIKEY
              valueFrom:
                secretKeyRef:
                  {{- if .Values.honeycomb.existingSecret }}
                  name: {{ .Values.honeycomb.existingSecret }}
                  {{- else }}
                  name: {{ include "honeycomb.fullname" . }}
                  {{- end }}
                  key: api-key
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: "/etc/honeycomb"
              readOnly: false
            - name: varlog
              mountPath: "/var/log"
              readOnly: false
            - name: varlibdockercontainers
              mountPath: "/var/lib/docker/containers"
              readOnly: true
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      volumes:
        - name: config
          configMap:
            items:
              - key: config.yaml
                path: config.yaml
            name: {{ include "honeycomb.agent.fullname" . }}
        - name: varlog
          hostPath:
            path: "/var/log"
        - name: varlibdockercontainers
          hostPath:
            path: "/var/lib/docker/containers"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
