{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "honeycomb.agent.fullname" . }}
  labels:
  {{- include "honeycomb.agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "honeycomb.agent.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "honeycomb.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}