{{- if not .Values.honeycomb.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "honeycomb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "honeycomb.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.honeycomb.apiKey | b64enc | quote }}
{{- end }}
