htp:
  resources:
    requests:
      memory: 100Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 100m
  prometheus:
    resources:
      requests:
        memory: 100Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 100m
  nats:
    resources:
      requests:
        memory: 100Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 100m
  jobs:
    resources:
      requests:
        memory: 100Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 100m
