honeycomb:
  # Honeycomb API key used to send events.
  apiKey: ""
  # The name of an existing secret containing the Honeycomb API key.
  existingSecret: ""
  # The key in the existing secret containing the Honeycomb API key (defaults to 'apiKey').
  existingSecretKey: "apiKey"
  # Honeycomb API endpoint events are sent to (defaults to 'https://api.honeycomb.io')
  endpoint: "https://api.honeycomb.io"
  # Honeycomb destination dataset for events (defaults to 'hny-network-agent')
  dataset: "hny-network-agent"
  # Honeycomb destination dataset for agent performance stats (defaults to 'hny-network-agent-stats')
  statsDataset: "hny-network-agent-stats"

image:
  repository: ghcr.io/honeycombio/network-agent
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# Allows adding extra environment variables to the network agent daemonset.
extraEnvVars:
  # - name: ENV_VAR
  #   value: value
