apiVersion: v2
name: observability-pipeline
description: Chart to deploy both OpenTelemetry Collector and Honeycomb Refinery
type: application
version: 0.0.37-alpha
appVersion: 0.0.1-alpha
keywords:
  - refinery
  - open-telemetry
  - honeycomb
  - observability
  - sampling
  - tracing
  - collector
home: https://honeycomb.io
sources:
  - https://github.com/honeycombio/refinery
  - https://github.com/open-telemetry/opentelemetry-collector-releases
icon: https://www.honeycomb.io/wp-content/themes/honeycomb/assets/img/logo.svg
maintainers:
  - name: Honeycomb
    email: pipeline-team@honeycomb.io
dependencies:
- name: refinery
  version: 2.15.3
  repository: "https://honeycombio.github.io/helm-charts"
