pipelineInstallationID: ""
team: ""
publicMgmtAPIKey: ""

refinery:
  image:
    repository: "honeycombio/refinery"
    tag: "2.9.3-htp-dev.1"
  config:
    Network:
      OpAMPEnabled: true
      OpAMPEndpoint: "ws://{{ include \"honeycomb-observability-pipeline.name\" . }}-beekeeper:4320/v1/opamp"
      OpAMPRecordUsage: false
    PrometheusMetrics:
      Enabled: false
    OTelMetrics:
      Enabled: true
    Logger:
      Type: honeycomb
  environment:
    - name: REFINERY_HONEYCOMB_API_KEY
      valueFrom:
        secretKeyRef:
          name: honeycomb-observability-pipeline
          key: api-key

beekeeper:
  resources: {}
  serviceAccount:
    create: true
    name: ""
  image:
    repository: "honeycombio/beekeeper"
    pullPolicy: IfNotPresent
    tag: "latest"
  endpoint: https://api.honeycomb.io:443
  persistentVolumeClaimName: ""
  defaultEnv:
    HONEYCOMB_MGMT_API_SECRET:
      content:
        valueFrom:
          secretKeyRef:
            name: honeycomb-observability-pipeline
            key: management-api-secret
    HONEYCOMB_API_KEY:
      content:
        valueFrom:
          secretKeyRef:
            name: honeycomb-observability-pipeline
            key: api-key
    TELEMETRY_ENDPOINT:
      enabled: true
      content:
        value: https://api.honeycomb.io:443
    TELEMETRY_KEY:
      enabled: true
      content:
        value: "${env:HONEYCOMB_API_KEY}"
    TELEMETRY_METRICS_DATASET:
      enabled: true
      content:
        value: "{{ .Values.primaryCollector.serviceName }}-metrics"
    LOG_LEVEL:
      enabled: true
      content:
        value: "info"
    HONEYCOMB_CONFIGURATION_KEY:
      enabled: false
      content:
        valueFrom:
          secretKeyRef:
            name: honeycomb-observability-pipeline
            key: configuration-key
  extraEnvs: []
  volumes: []
  volumeMounts: []
  telemetry:
    enabled: true
    config:
      file_format: "0.3"
      resource:
        schema_url: https://opentelemetry.io/schemas/1.26.0
        attributes:
          - name: service.name
            value: "beekeeper"
          - name: service.version
            value: "0.0.1"
      propagator:
        composite:
          - tracecontext
          - baggage
      tracer_provider:
        processors:
          - batch:
              exporter:
                otlp:
                  protocol: http/protobuf
                  endpoint: ${TELEMETRY_ENDPOINT}
                  headers:
                  - name: "x-honeycomb-team"
                    value: ${HONEYCOMB_API_KEY}
      logger_provider:
        processors:
          - batch:
              exporter:
                otlp:
                  protocol: http/protobuf
                  endpoint: ${TELEMETRY_ENDPOINT}
                  headers:
                  - name: "x-honeycomb-team"
                    value: ${HONEYCOMB_API_KEY}


primaryCollector:
  serviceName: "primary-collector"
  serviceAccount:
    create: true
    name: ""
  service:
    enabled: true
    ports:
      - name: otlp
        port: 4317
        targetPort: 4317
        protocol: TCP
        appProtocol: grpc
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP
  resources: {}
  replicaCount: 2
  image:
    repository: "honeycombio/supervised-collector"
    pullPolicy: IfNotPresent
    tag: "latest"
  defaultEnv:
    HONEYCOMB_API_KEY:
      enabled: true
      content:
        valueFrom:
          secretKeyRef:
            name: honeycomb-observability-pipeline
            key: api-key
  extraEnvs: []
  volumes: []
  volumeMounts: []
  opampsupervisor:
    telemetry:
      enabled: true
      defaultEndpoint: https://api.honeycomb.io:443
      defaultServiceName: opamp-supervisor
      config:
        resource:
          'service.name': '{{ .Values.primaryCollector.opampsupervisor.telemetry.defaultServiceName }}'
        logs:
          level: info
          processors:
            - batch:
                exporter:
                  otlp:
                    protocol: http/protobuf
                    endpoint: '{{ .Values.primaryCollector.opampsupervisor.telemetry.defaultEndpoint }}'
                    headers:
                    - name: "x-honeycomb-team"
                      value: ${HONEYCOMB_API_KEY}
