# The ID of your pipeline installation.
# This can be found on the Pipeline Installations page in the Honeycomb UI.
pipelineInstallationID: ""

# The public ID of your Honeycomb Management API key.
# See https://docs.honeycomb.io/configure/teams/manage-api-keys/#find-management-api-keys for more details.
publicMgmtAPIKey: ""

global:
  # This setting configures the default endpoints. All endpoints can still be configured and will take precedence.
  # The default value is '' (unset). When unset, U.S. values will be used for any unconfigured endpoints.
  # Other valid values are:
  #  - production-eu
  #
  # When 'production-eu' is set, the following settings are configured:
  #  refinery:
  #    config:
  #      Network:
  #        HoneycombAPI: https://api.eu1.honeycomb.io
  #      HoneycombLogger:
  #        APIHost: https://api.eu1.honeycomb.io
  #      LegacyMetrics:
  #        APIHost: https://api.eu1.honeycomb.io
  #      OTelMetrics:
  #        APIHost: https://api.eu1.honeycomb.io
  #      OTelTracing:
  #        APIHost: https://api.eu1.honeycomb.io
  #  beekeeper:
  #    endpoint: https://api.eu1.honeycomb.io
  #    defaultEnv:
  #      TELEMETRY_ENDPOINT:
  #        content:
  #          value: https://api.eu1.honeycomb.io
  #  primaryCollector:
  #    opampsupervisor
  #      telemetry:
  #        defaultEndpoint: https://api.eu1.honeycomb.io
  #
  # Any values you've configured will take precedence.
  region: ""

# Configuration options for Refinery.
# For a complete list of configuration options see https://github.com/honeycombio/helm-charts/tree/main/charts/refinery#configuration.
refinery:
  config:
    OpAMP:
      Enabled: true
      Endpoint: "ws://{{ include \"honeycomb-observability-pipeline.beekeeperName\" . }}:4320/v1/opamp"
      RecordUsage: false
    PrometheusMetrics:
      Enabled: false
    OTelMetrics:
      Enabled: true
    Logger:
      Type: honeycomb
  environment:
    # Default key for the HPSF Honeycomb Exporter
    - name: HONEYCOMB_EXPORTER_APIKEY
      valueFrom:
        secretKeyRef:
          name: honeycomb-observability-pipeline
          key: api-key
    # Env var for exporting refinery internal telemetry
    - name: REFINERY_HONEYCOMB_API_KEY
      valueFrom:
        secretKeyRef:
          name: honeycomb-observability-pipeline
          key: api-key

# Configuration options for Beekeeper.
beekeeper:
  image:
    repository: "honeycombio/beekeeper"
    pullPolicy: IfNotPresent
    tag: "v0.0.14-alpha"

  # The Honeycomb API endpoint Beekeeper should use.
  # When unset (the default), Beekeeper will use https://api.honeycomb.io
  endpoint: ""

  # Allows configuring Beekeeper environment variables. 
  defaultEnv:
    HONEYCOMB_MGMT_API_SECRET:
      content:
        valueFrom:
          secretKeyRef:
            name: honeycomb-observability-pipeline
            key: management-api-secret
    HONEYCOMB_API_KEY:
      content:
        valueFrom:
          secretKeyRef:
            name: honeycomb-observability-pipeline
            key: api-key
    LOG_LEVEL:
      enabled: true
      content:
        value: "info"
    # Enabled this env var if you want Beekeeper to create markers during rollouts.
    HONEYCOMB_CONFIGURATION_KEY:
      enabled: false
      content:
        valueFrom:
          secretKeyRef:
            name: honeycomb-observability-pipeline
            key: configuration-key
  extraEnvs: []

  # Resource limits & requests.
  # It is HIGHLY recommended to set resource limits.
  # resources:
  #   limits:
  #     cpu: 50m
  #     memory: 50Mi
  resources: {}

  serviceAccount:
    create: true
    # Name of the service account to use if not creating a new one.
    name: ""

  persistentVolumeClaimName: ""
  volumes: []
  volumeMounts: []

  # Settings for Beekeeper's internal telemetry.
  telemetry:
    enabled: true
    # Beekeeper's OTel SDK Configuration.
    config:
      file_format: "0.3"
      resource:
        schema_url: https://opentelemetry.io/schemas/1.26.0
        attributes:
          - name: service.name
            value: "beekeeper"
          - name: service.version
            value: "0.0.1"
      propagator:
        composite:
          - tracecontext
          - baggage
      tracer_provider:
        processors:
          - batch:
              exporter:
                otlp:
                  protocol: http/protobuf
                  endpoint: '{{ include "honeycomb-observability-pipeline.beekeeper.telemetryEndpoint" . }}'
                  headers:
                  - name: "x-honeycomb-team"
                    value: ${HONEYCOMB_API_KEY}
      logger_provider:
        processors:
          - batch:
              exporter:
                otlp:
                  protocol: http/protobuf
                  endpoint: '{{ include "honeycomb-observability-pipeline.beekeeper.telemetryEndpoint" . }}'
                  headers:
                  - name: "x-honeycomb-team"
                    value: ${HONEYCOMB_API_KEY}

# Configuration options for the Primary Collector.
primaryCollector:
  serviceAccount:
    create: true
    # Name of the service account to use if not creating a new one.
    name: ""
  
  service:
    enabled: true
    ports:
      - name: otlp
        port: 4317
        targetPort: 4317
        protocol: TCP
        appProtocol: grpc
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP

  # Resource limits & requests.
  # It is HIGHLY recommended to set resource limits.
  # resources:
  #   limits:
  #     cpu: 250m
  #     memory: 512Mi
  resources: {}

  # Number of replicas to deploy
  replicaCount: 2

  image:
    repository: "honeycombio/supervised-collector"
    pullPolicy: IfNotPresent
    tag: "v0.0.6"

  defaultEnv:
    HONEYCOMB_API_KEY:
      enabled: true
      content:
        valueFrom:
          secretKeyRef:
            name: honeycomb-observability-pipeline
            key: api-key
  extraEnvs: []

  volumes: []
  volumeMounts: []

  # configuration options for the agent (a collector) the OpAMP Supervisor manages
  agent:
    telemetry:
      enabled: true
      defaultEndpoint: ""
      defaultServiceName: "primary-collector"
      file: /etc/agent/config.yaml
      config:
        metrics:
          readers:
            - periodic:
                exporter:
                  otlp:
                    endpoint: '{{ include "honeycomb-observability-pipeline.primaryCollector.agent.telemetry.defaultEndpoint" . }}'
                    headers:
                      - name: x-honeycomb-dataset
                        value: primary-collector-metrics
                      - name: x-honeycomb-team
                        value: ${env:HONEYCOMB_API_KEY}
                    protocol: http/protobuf
                    temporality_preference: delta
        logs:
          encoding: json
          processors:
            - batch:
                exporter:
                  otlp:
                    endpoint: '{{ include "honeycomb-observability-pipeline.primaryCollector.agent.telemetry.defaultEndpoint" . }}'
                    headers:
                      - name: x-honeycomb-team
                        value: ${env:HONEYCOMB_API_KEY}
                    protocol: http/protobuf
                    
  # configuration options for the OpAMP Supervisor.
  opampsupervisor:
    telemetry:
      # Enables the OpAMP Supervisor's internal telemetry.
      enabled: true
      # Default endpoint for telemetry data.
      # When unset (the default), the endpoint will be set to https://api.honeycomb.io.
      defaultEndpoint: ""
      defaultServiceName: opamp-supervisor
      # The OpAMP Supervisor's configuration file.
      config:
        resource:
          'service.name': '{{ .Values.primaryCollector.opampsupervisor.telemetry.defaultServiceName }}'
        logs:
          level: info
          processors:
            - batch:
                exporter:
                  otlp:
                    protocol: http/protobuf
                    endpoint: '{{ include "honeycomb-observability-pipeline.primaryCollector.opampsupervisor.telemetry.defaultEndpoint" . }}'
                    headers:
                    - name: "x-honeycomb-team"
                      value: ${HONEYCOMB_API_KEY}
  