{{- if .Values.refinery.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "honeycomb-observability-pipeline.fullname" . }}-beekeeper
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "honeycomb-observability-pipeline.beekeeper.labels" . | nindent 4 }}
    app.kubernetes.io/component: beekeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "honeycomb-observability-pipeline.beekeeper.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        {{- include "honeycomb-observability-pipeline.beekeeper.configTemplateChecksumAnnotation" . | nindent 8 }}
      labels:
        {{- include "honeycomb-observability-pipeline.beekeeper.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: beekeeper
    spec:
      serviceAccountName: {{ include "honeycomb-observability-pipeline.beekeeper.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.beekeeper.image.repository }}:{{ .Values.beekeeper.image.tag }}"
          imagePullPolicy: {{ .Values.beekeeper.image.pullPolicy }}
          {{- if or .Values.beekeeper.telemetry.enabled .Values.beekeeper.persistentVolumeClaimName }}
          args:
          {{- if .Values.beekeeper.telemetry.enabled }}
            - -otel-config
            - /etc/beekeeper/otel-config.yaml
          {{- end }}
          {{- if .Values.beekeeper.persistentVolumeClaimName }}
            - -config-cache-path
            - /app/beekeeper/cache
          {{- end }}
          {{- end }}
          env:
            - name: K8S_NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8S_POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: pipelineInstallationID={{ .Values.beekeeper.pipelineInstallationID }},k8s.namespace.name=$(K8S_NAMESPACE_NAME),k8s.node.name=$(K8S_NODE_NAME),k8s.pod.name=$(K8S_POD_NAME),k8s.pod.uid=$(K8S_POD_UID)
            - name: HONEYCOMB_API
              value: {{ .Values.beekeeper.endpoint }}
            - name: HONEYCOMB_TEAM
              value: {{ .Values.beekeeper.team }}
            - name: HONEYCOMB_INSTALLATION_ID
              value: {{ .Values.beekeeper.pipelineInstallationID }}
            - name: HONEYCOMB_MGMT_API_KEY
              value: {{ .Values.beekeeper.publicMgmtKey }}
            - name: HONEYCOMB_MGMT_API_SECRET
              {{- toYaml .Values.beekeeper.defaultEnv.HONEYCOMB_MGMT_API_SECRET.content | nindent 14 }}  
            - name: HONEYCOMB_API_KEY
              {{- toYaml .Values.beekeeper.defaultEnv.HONEYCOMB_API_KEY.content | nindent 14 }}  
            {{- if .Values.beekeeper.defaultEnv.TELEMETRY_ENDPOINT.enabled }}
            - name: TELEMETRY_ENDPOINT
              {{- toYaml .Values.beekeeper.defaultEnv.TELEMETRY_ENDPOINT.content | nindent 14 }}  
            {{- end }}
            {{- if .Values.beekeeper.defaultEnv.TELEMETRY_KEY.enabled }}
            - name: TELEMETRY_KEY
              {{- toYaml .Values.beekeeper.defaultEnv.TELEMETRY_KEY.content | nindent 14 }}  
            {{- end }}
            {{- if .Values.beekeeper.defaultEnv.TELEMETRY_METRICS_DATASET.enabled }}
            - name: TELEMETRY_METRICS_DATASET
              {{- tpl (toYaml .Values.beekeeper.defaultEnv.TELEMETRY_METRICS_DATASET.content) . | nindent 14 }}  
            {{- end }}
            {{- if .Values.beekeeper.defaultEnv.LOG_LEVEL.enabled }}
            - name: LOG_LEVEL
              {{- toYaml .Values.beekeeper.defaultEnv.LOG_LEVEL.content | nindent 14 }}  
            {{- end }}
            {{- with .Values.beekeeper.extraEnvs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.beekeeper.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.beekeeper.volumeMounts .Values.beekeeper.telemetry.enabled .Values.beekeeper.persistentVolumeClaimName }}
          volumeMounts:
          {{- if .Values.beekeeper.telemetry.enabled }}
            - name: otel-config
              mountPath: /etc/beekeeper
          {{- end }}  
          {{- if .Values.beekeeper.persistentVolumeClaimName }}
            - name: latest-config-cache
              mountPath: /app/beekeeper/cache
              readonly: false
          {{- end }}
          {{- with .Values.beekeeper.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          ports:
            - name: config
              containerPort: 4321
              protocol: TCP
            - name: opamp
              containerPort: 4320
              protocol: TCP
      {{- if or .Values.beekeeper.volumeMounts .Values.beekeeper.telemetry.enabled .Values.beekeeper.persistentVolumeClaimName }}
      volumes:
      {{- if .Values.beekeeper.telemetry.enabled }}
        - name: otel-config
          configMap:
            name: {{ include "honeycomb-observability-pipeline.fullname" . }}-beekeeper
            items:
              - key: otel-config
                path: otel-config.yaml
      {{- end }}  
      {{- if .Values.beekeeper.persistentVolumeClaimName }}
        - name: latest-config-cache
          persistentVolumeClaimName: {{ .Values.beekeeper.persistentVolumeClaimName }}
      {{- end }}
      {{- with .Values.beekeeper.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
{{- end }}
