apiVersion: v1
kind: Service
metadata:
  name: {{ include "honeycomb-observability-pipeline.fullname" . }}-beekeeper
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "honeycomb-observability-pipeline.beekeeper.labels" . | nindent 4 }}
    app.kubernetes.io/component: beekeeper
spec:
  type: ClusterIP
  ports:
    - port: 4321
      targetPort: "config"
      protocol: TCP
      name: config
    - port: 4320
      targetPort: "opamp"
      protocol: TCP
      name: opamp
  selector:
    {{- include "honeycomb-observability-pipeline.beekeeper.selectorLabels" . | nindent 4 }}
