{{- if .Values.beekeeper.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "honeycomb-observability-pipeline.beekeeper.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "honeycomb-observability-pipeline.beekeeper.labels" . | nindent 4 }}
    app.kubernetes.io/component: beekeeper
{{- end }}
