{{- if and .Values.collector.enabled .Values.collector.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "honeycomb-observability-pipeline.collector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "honeycomb-observability-pipeline.collector.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
{{- end }}
