{{- if .Values.controlPlane.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "honeycomb-observability-pipeline.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "honeycomb-observability-pipeline.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
{{- end }}
