{{- if .Values.refinery.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "honeycomb-observability-pipeline.fullname" . }}-control-plane
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "honeycomb-observability-pipeline.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
spec:
  type: ClusterIP
  ports:
    - port: 4321
      targetPort: "config"
      protocol: TCP
      name: config
  selector:
    {{- include "honeycomb-observability-pipeline.selectorLabels" . | nindent 4 }}
{{- end }}
