{{- if .Values.refinery.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "honeycomb-observability-pipeline.fullname" . }}-control-plane
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "honeycomb-observability-pipeline.controlPlane.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "honeycomb-observability-pipeline.controlPlane.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "honeycomb-observability-pipeline.controlPlane.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: control-plane
    spec:
      serviceAccountName: {{ include "honeycomb-observability-pipeline.controlPlane.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.controlPlane.image.repository }}:{{ .Values.controlPlane.image.tag }}"
          imagePullPolicy: {{ .Values.controlPlane.image.pullPolicy }}
          args:
          {{- if .Values.controlPlane.telemetry.enabled }}
            - -otel-config
            - /etc/straws-control-plane/otel-config.yaml
          {{- end }}
          {{- if .Values.controlPlane.persistentVolumeClaimName }}
            - -config-cache-path
            - /app/straws-control-plane/cache
          {{- end }}
          env:
            - name: HONEYCOMB_API
              value: {{ .Values.controlPlane.endpoint }}
            - name: HONEYCOMB_TEAM
              value: {{ .Values.controlPlane.team }}
            - name: HONEYCOMB_INSTALLATION_ID
              value: {{ .Values.controlPlane.pipelineInstallationID }}
            - name: HONEYCOMB_MGMT_API_KEY
              value: {{ .Values.controlPlane.publicMgmtKey }}
            {{- with .Values.controlPlane.environment }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.controlPlane.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.controlPlane.volumeMounts .Values.controlPlane.telemetry.enabled }}
          volumeMounts:
          {{- if .Values.controlPlane.telemetry.enabled }}
            - name: otel-config
              mountPath: /etc/straws-control-plane
          {{- end }}  
          {{- if .Values.controlPlane.persistentVolumeClaimName }}
            - name: latest-config-cache
              mountPath: /app/straws-control-plane/cache
              readonly: false
          {{- end }}
          {{- with .Values.controlPlane.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          ports:
            - name: config
              containerPort: 4321
              protocol: TCP
            - name: opamp
              containerPort: 4320
              protocol: TCP
      {{- if or .Values.controlPlane.volumeMounts .Values.controlPlane.telemetry.enabled }}
      volumes:
      {{- if .Values.controlPlane.telemetry.enabled }}
        - name: otel-config
          configMap:
            name: {{ include "honeycomb-observability-pipeline.fullname" . }}-control-plane
            items:
              - key: otel-config
                path: otel-config.yaml
      {{- end }}  
      {{- if .Values.controlPlane.persistentVolumeClaimName }}
        - name: latest-config-cache
          persistentVolumeClaimName: {{ .Values.controlPlane.persistentVolumeClaimName }}
      {{- end }}
      {{- with .Values.controlPlane.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
{{- end }}
