{{- if .ValuesprimaryCollector.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "honeycomb-observability-pipelineprimaryCollector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "honeycomb-observability-pipelineprimaryCollector.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
{{- end }}
