apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "honeycomb-observability-pipeline.fullname" . }}-primary-collector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "honeycomb-observability-pipelineprimaryCollector.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
spec:
  replicas: {{ .ValuesprimaryCollector.replicaCount }}
  selector:
    matchLabels:
      {{- include "honeycomb-observability-pipelineprimaryCollector.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        {{- include "honeycomb-observability-pipelineprimaryCollector.configTemplateChecksumAnnotation" . | nindent 8 }}
      labels:
        {{- include "honeycomb-observability-pipelineprimaryCollector.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: collector
    spec:
      serviceAccountName: {{ include "honeycomb-observability-pipelineprimaryCollector.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .ValuesprimaryCollector.image.repository }}:{{ .ValuesprimaryCollector.image.tag }}"
          imagePullPolicy: {{ .ValuesprimaryCollector.image.pullPolicy }}
          args:
            - --config
            - /etc/opampsupervisor/config.yaml
          env:
            - name: K8S_NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8S_POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: STRAWS_COLLECTOR_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: pipelineInstallationID={{ .Values.pipelineInstallationID }},k8s.namespace.name=$(K8S_NAMESPACE_NAME),k8s.node.name=$(K8S_NODE_NAME),k8s.pod.name=$(K8S_POD_NAME),k8s.pod.uid=$(K8S_POD_UID)
            {{- if .ValuesprimaryCollector.defaultEnv.HONEYCOMB_API_KEY.enabled }}
            - name: HONEYCOMB_API_KEY
              {{- toYaml .ValuesprimaryCollector.defaultEnv.HONEYCOMB_API_KEY.content | nindent 14 }}  
            {{- end }}
            {{- with .ValuesprimaryCollector.extraEnvs }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .ValuesprimaryCollector.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/opampsupervisor
          {{- with .Values.beekeeper.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "honeycomb-observability-pipeline.fullname" . }}-primary-collector
            items:
              - key: config
                path: config.yaml
      {{- with .ValuesprimaryCollector.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
