apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "honeycomb-observability-pipeline.fullname" . }}-primary-collector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "honeycomb-observability-pipeline.primaryCollector.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
data:
  config: |
  {{- include "honeycomb-observability-pipeline.primaryCollector.config" . | nindent 4 -}}
