{{- if .Values.primaryCollector.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "honeycomb-observability-pipeline.fullname" . }}-primary-collector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "honeycomb-observability-pipeline.primaryCollector.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
spec:
  type: ClusterIP
  ports:
    {{- toYaml .Values.primaryCollector.service.ports | nindent 4 }}
  selector:
    {{- include "honeycomb-observability-pipeline.primaryCollector.selectorLabels" . | nindent 4 }}
{{- end }}
