resources:
  limits:
    cpu: 100m
    memory: 200M
  requests:
    cpu: 100m
    memory: 200M

redis:
  resources:
    limits:
      cpu: 100m
      memory: 200M
    requests:
      cpu: 100m
      memory: 200M
